export const ASYNC_PATTERN_GET_STATUS = 'IAsyncPatternGetStatus';
export const ASYNC_PATTERN_START_PROCESS = 'IAsyncPatternStartProcess';
export const ASYNC_MODULE_OPTIONS = 'ASYNC_MODULE_OPTIONS';
export const ASYNC_PATTERN_QUEUE = 'ASYNC_PATTERN_QUEUE';
export const ASYNC_JOB_NAME = 'ASYNC_JOB_NAME';
export const ASYNC_STATUS_BASE_PATH = 'ASYNC_STATUS_BASE_PATH';
export const ASYNC_STATUS_LOCATION_BASE_PATH = 'ASYNC_STATUS_LOCATION_BASE_PATH';
