name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.20.2
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:package

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
